apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  selector:
    matchLabels:
      app: healthcare
  replicas: 1
  template: 
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: ${REPOSITORY_TAG}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: production-microservice
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: service-healthcare

spec:
  selector:
    app: healthcare

  ports:
    - name: http
      port: 8090
      nodePort: 30020

  type: NodePort
